export enum IconType {
    BIN = "BIN",
    FOLDER = "FOLDER",
    TASK = "TASK",
    NOTE = "NOTE",
    FILE = "FILE",
    INFORMATION = "INFORMATION",
    IMAGE = "IMAGE",
    VIDEO = "VIDEO",
    AUDIO = "AUDIO",
    PDF = "PDF",
    USER = "USER",
    USERS = "USERS",
    CALENDAR = "CALENDAR",
    CLOCK = "CLOCK",
    WARNING = "WARNING",
    CHECK = "CHECK",
    STAR = "STAR",
    HEART = "HEART",
    TAG = "TAG",
    LINK = "LINK",

    PLAN = "PLAN",
    DETAIL = "DETAIL",
    IMPORTANT = "IMPORTANT",
    URGENT = "URGENT",
}
